services:
  - type: web
    name: soquick
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: MEDIAPIPE_MODEL_PATH
        value: pose_landmarker_lite.task
    healthCheckPath: /health
